import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import type { AddressInfo } from 'node:net';
import { createApp } from '../server/src/index.js';
import { db } from '../server/src/db.js';
import type { AiProvider, AiResult } from '../server/src/aiProvider.js';

class DeterministicProposalProvider implements AiProvider {
  calls = 0;
  constructor(private readonly result: AiResult) {}
  async generate(): Promise<AiResult> { this.calls += 1; return this.result; }
}
type JsonResponse = { json: any; response: Response };
let server: ReturnType<typeof createApp> extends never ? never : ReturnType<ReturnType<typeof createApp>['listen']>;
let baseUrl = '';
async function request(path: string, init: RequestInit = {}, cookie?: string): Promise<JsonResponse> { const headers = new Headers(init.headers); headers.set('content-type', 'application/json'); if (cookie) headers.set('cookie', cookie); const response = await fetch(`${baseUrl}${path}`, { ...init, headers }); return { response, json: response.status === 204 ? undefined : await response.json() }; }
function cookie(response: Response) { return response.headers.get('set-cookie')!.split(';', 1)[0]; }

describe('visual proposal PostgreSQL persistence and boundaries', () => {
  const suffix = `${Date.now()}-${Math.random().toString(16).slice(2)}`; const emailA = `proposal-a-${suffix}@example.com`; const emailB = `proposal-b-${suffix}@example.com`;
  let cookieA = ''; let cookieB = ''; let projectA = ''; let projectB = ''; let conversationA = ''; let proposalId = ''; let provider: DeterministicProposalProvider;
  beforeAll(async () => { await db.$connect(); provider = new DeterministicProposalProvider({ assistantText: 'Preparei uma proposta aguardando revisão.', proposedActions: [{ type: 'CREATE_NODE', clientActionId: 'action-1', nodeType: 'TASK', title: 'Produzir capa', content: 'Criar a capa oficial' }, { type: 'CREATE_NODE', clientActionId: 'action-2', nodeType: 'DECISION', title: 'Definir preço', content: 'Escolher a faixa de preço' }] }); const app = createApp({ aiProvider: provider }); server = app.listen(0); await new Promise<void>(resolve => server.once('listening', resolve)); baseUrl = `http://127.0.0.1:${(server.address() as AddressInfo).port}`; const registeredA = await request('/api/auth/register', { method: 'POST', body: JSON.stringify({ name: 'Proposal A', email: emailA, password: 'A-secure-password-123' }) }); cookieA = cookie(registeredA.response); const registeredB = await request('/api/auth/register', { method: 'POST', body: JSON.stringify({ name: 'Proposal B', email: emailB, password: 'B-secure-password-123' }) }); cookieB = cookie(registeredB.response); projectA = (await request('/api/projects', { method: 'POST', body: JSON.stringify({ name: 'Visual A' }) }, cookieA)).json.project.id; projectB = (await request('/api/projects', { method: 'POST', body: JSON.stringify({ name: 'Visual B' }) }, cookieB)).json.project.id; conversationA = (await request(`/api/projects/${projectA}/conversations`, { method: 'POST', body: '{}' }, cookieA)).json.conversation.id; });
  afterAll(async () => { if (projectA) await db.project.delete({ where: { id: projectA } }).catch(() => undefined); if (projectB) await db.project.delete({ where: { id: projectB } }).catch(() => undefined); await db.profile.deleteMany({ where: { email: { in: [emailA, emailB] } } }).catch(() => undefined); await new Promise<void>(resolve => server?.close(() => resolve())); await db.$disconnect(); });
  it('persists a validated pending proposal on the assistant message without creating nodes', async () => { const before = await request(`/api/projects/${projectA}`, {}, cookieA); const sent = await request(`/api/projects/${projectA}/conversations/${conversationA}/messages`, { method: 'POST', body: JSON.stringify({ content: 'Organize isto no canvas', contextNodeIds: [] }) }, cookieA); expect(sent.response.status).toBe(201); expect(sent.json.assistantMessage.visualProposal.payload.proposedActions).toHaveLength(2); proposalId = sent.json.assistantMessage.visualProposal.id; expect(sent.json.assistantMessage.visualProposal).toMatchObject({ projectId: projectA, conversationId: conversationA, status: 'PENDING', protocolVersion: '1.0' }); expect(provider.calls).toBe(1); const after = await request(`/api/projects/${projectA}`, {}, cookieA); expect(after.json.project.nodes).toHaveLength(before.json.project.nodes.length); });
  it('does not duplicate a proposal for confirmations or ordinary questions, but allows a different explicit request', async () => { const original = await request(`/api/projects/${projectA}/visual-proposals/${proposalId}`, {}, cookieA); for (const content of ['ok, aprovado', 'confirmo', 'pode seguir', 'obrigado', 'cancele', 'rejeitado', 'Como está o projeto?']) { const response = await request(`/api/projects/${projectA}/conversations/${conversationA}/messages`, { method: 'POST', body: JSON.stringify({ content, contextNodeIds: [] }) }, cookieA); expect(response.response.status).toBe(201); expect(response.json.assistantMessage.visualProposal).toBeNull(); if (content === 'ok, aprovado') expect(response.json.assistantMessage.content).toBe('A proposta permanece aguardando revisão. A aplicação ao canvas ainda não está disponível.'); } const different = await request(`/api/projects/${projectA}/conversations/${conversationA}/messages`, { method: 'POST', body: JSON.stringify({ content: 'Crie três blocos no canvas', contextNodeIds: [] }) }, cookieA); expect(different.json.assistantMessage.visualProposal.payload.proposedActions).toHaveLength(2); const conversation = await request(`/api/projects/${projectA}/conversations/${conversationA}`, {}, cookieA); expect(conversation.json.conversation.messages.filter((message: { visualProposal?: unknown }) => message.visualProposal).length).toBe(2); const reloaded = await request(`/api/projects/${projectA}/visual-proposals/${proposalId}`, {}, cookieA); expect(JSON.stringify(reloaded.json.proposal.payload)).toBe(JSON.stringify(original.json.proposal.payload)); const project = await request(`/api/projects/${projectA}`, {}, cookieA); expect(project.json.project.nodes).toHaveLength(0); });
  it('reads only inside the owning project and keeps the proposal immutable', async () => { const read = await request(`/api/projects/${projectA}/visual-proposals/${proposalId}`, {}, cookieA); expect(read.response.status).toBe(200); const original = JSON.stringify(read.json.proposal.payload); const attempted = await fetch(`${baseUrl}/api/projects/${projectA}/visual-proposals/${proposalId}`, { method: 'PATCH', headers: { 'content-type': 'application/json', cookie: cookieA }, body: JSON.stringify({ status: 'EXECUTED', payload: {} }) }); expect(attempted.status).toBe(404); expect(JSON.stringify((await request(`/api/projects/${projectA}/visual-proposals/${proposalId}`, {}, cookieA)).json.proposal.payload)).toBe(original); expect((await request(`/api/projects/${projectA}/visual-proposals/${proposalId}`, {}, cookieB)).response.status).toBe(404); expect((await request(`/api/projects/${projectB}/visual-proposals/${proposalId}`, {}, cookieB)).response.status).toBe(404); });
  it('keeps assistant text when the entire proposal is invalid', async () => { const invalidProvider = new DeterministicProposalProvider({ assistantText: 'Resposta textual segura', proposedActions: [{ type: 'CREATE_NODE', clientActionId: 'same', nodeType: 'TASK', title: 'A', content: 'B' }, { type: 'CREATE_NODE', clientActionId: 'same', nodeType: 'TASK', title: 'C', content: 'D' }] }); const invalidApp = createApp({ aiProvider: invalidProvider }); const invalidServer = invalidApp.listen(0); await new Promise<void>(resolve => invalidServer.once('listening', resolve)); const invalidBase = baseUrl; baseUrl = `http://127.0.0.1:${(invalidServer.address() as AddressInfo).port}`; const sent = await request(`/api/projects/${projectA}/conversations/${conversationA}/messages`, { method: 'POST', body: JSON.stringify({ content: 'Resposta normal', contextNodeIds: [] }) }, cookieA); expect(sent.response.status).toBe(201); expect(sent.json.assistantMessage.content).toBe('Resposta textual segura'); expect(sent.json.assistantMessage.visualProposal).toBeNull(); await new Promise<void>(resolve => invalidServer.close(() => resolve())); baseUrl = invalidBase; });
});
