import { useEffect, useState } from 'react';
import { api, type ChatMessage, type Node } from './api';

export function AiPanel({ projectId, nodes, selectedIds, contextIds, onContextChange }: { projectId: string; nodes: Node[]; selectedIds: Set<string>; contextIds: string[]; onContextChange: (ids: string[]) => void }) {
  const [conversationId, setConversationId] = useState<string | null>(null); const [messages, setMessages] = useState<ChatMessage[]>([]); const [content, setContent] = useState(''); const [loading, setLoading] = useState(true); const [sending, setSending] = useState(false); const [error, setError] = useState('');
  useEffect(() => { let active = true; setLoading(true); api.conversations(projectId).then(async result => { const latest = result.conversations[0]; if (!latest) return; const detail = await api.conversation(projectId, latest.id); if (active) { setConversationId(latest.id); setMessages(detail.conversation.messages ?? []); } }).catch(() => active && setError('Não foi possível carregar a conversa.')).finally(() => active && setLoading(false)); return () => { active = false; }; }, [projectId]);
  const contextNodes = contextIds.map(id => nodes.find(node => node.id === id)).filter((node): node is Node => Boolean(node));
  const useSelection = () => onContextChange([...new Set([...contextIds, ...selectedIds])]);
  const send = async (event: React.FormEvent) => { event.preventDefault(); if (!content.trim() || sending) return; setSending(true); setError(''); try { const id = conversationId ?? (await api.createConversation(projectId)).conversation.id; const result = await api.sendMessage(projectId, id, { content: content.trim(), contextNodeIds: contextIds }); setConversationId(id); setMessages(current => [...current, result.userMessage, result.assistantMessage]); setContent(''); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Falha ao enviar.'); } finally { setSending(false); } };
  return <aside className="assistant ai-panel"><div className="eyebrow">ORION AI</div><h2>Contexto</h2><div className="ai-context-head"><span>{contextNodes.length} elemento{contextNodes.length === 1 ? '' : 's'} no contexto</span>{contextNodes.length > 0 && <button onClick={() => onContextChange([])}>Limpar</button>}</div><div className="ai-context-list">{contextNodes.map(node => <div className="ai-context-chip" key={node.id}><span><b>{node.type}</b> · {node.title}</span><button aria-label={`Remover ${node.title}`} onClick={() => onContextChange(contextIds.filter(id => id !== node.id))}>×</button></div>)}</div>{selectedIds.size > 0 && <button className="context-action" onClick={useSelection}>Usar como contexto ({selectedIds.size})</button>}<div className="ai-divider" />{loading ? <p className="muted">Carregando conversa…</p> : <div className="ai-messages">{messages.length === 0 && <p className="muted">Selecione nodes, use-os como contexto e faça uma pergunta.</p>}{messages.map(message => <div className={`ai-message ${message.role}`} key={message.id}><span className="ai-role">{message.role === 'user' ? 'Você' : 'Orion'}</span><p>{message.content}</p>{message.role === 'user' && message.contextNodes && message.contextNodes.length > 0 && <details><summary>Usou {message.contextNodes.length} elementos</summary>{message.contextNodes.map(snapshot => <div key={snapshot.nodeId}>{snapshot.titleSnapshot}</div>)}</details>}</div>)}</div>}<form className="ai-composer" onSubmit={send}><textarea value={content} onChange={event => setContent(event.target.value)} placeholder="Digite uma mensagem…" maxLength={8000} disabled={sending} /><button className="primary" disabled={sending || !content.trim()}>{sending ? 'Enviando…' : 'Enviar'}</button></form>{error && <div className="error ai-error">{error} {conversationId && <button onClick={() => setError('')}>Fechar</button>}</div>}</aside>;
}
