export type NodeType = 'note'|'document'|'ai_response'|'task'|'decision'|'prompt'|'file'|'frame';
export type Node = { id: string; type: NodeType; title: string; content: string; positionX: number; positionY: number; width: number; height: number; status?: string | null; tags: string[] };
export type Edge = { id: string; sourceNodeId: string; targetNodeId: string; relationType: string; label?: string | null };
export const relationTypes = ['related_to', 'depends_on', 'generates', 'derived_from', 'supports', 'contradicts', 'blocks', 'references'] as const;
export type RelationType = typeof relationTypes[number];
export const relationLabels: Record<RelationType, string> = { related_to: 'relaciona', depends_on: 'depende de', generates: 'gera', derived_from: 'deriva de', supports: 'suporta', contradicts: 'contradiz', blocks: 'bloqueia', references: 'referencia' };
export type Project = { id: string; name: string; description?: string | null; icon: string; color: string; isArchived: boolean; updatedAt: string };
async function request<T>(path: string, init?: RequestInit): Promise<T> { const response = await fetch(path, { credentials: 'include', headers: { 'Content-Type': 'application/json', ...(init?.headers ?? {}) }, ...init }); if (!response.ok) { const error = await response.json().catch(() => ({})); throw new Error(error.error ?? `HTTP_${response.status}`); } return response.status === 204 ? undefined as T : response.json(); }
export const api = { me: () => request<{ user: { id: string; name: string; email: string } }>('/api/auth/me'), login: (body: object) => request('/api/auth/login', { method: 'POST', body: JSON.stringify(body) }), register: (body: object) => request('/api/auth/register', { method: 'POST', body: JSON.stringify(body) }), logout: () => request('/api/auth/logout', { method: 'POST' }), projects: () => request<{ projects: Project[] }>('/api/projects'), createProject: (body: object) => request<{ project: Project }>('/api/projects', { method: 'POST', body: JSON.stringify(body) }), project: (id: string) => request<{ project: Project & { nodes: Node[]; edges: Edge[] }; viewState: { viewportX: number; viewportY: number; zoom: number } | null }>(`/api/projects/${id}`), updateProject: (id: string, body: object) => request(`/api/projects/${id}`, { method: 'PATCH', body: JSON.stringify(body) }), createNode: (projectId: string, body: object) => request<{ node: Node }>(`/api/projects/${projectId}/nodes`, { method: 'POST', body: JSON.stringify(body) }), updateNode: (projectId: string, nodeId: string, body: object) => request<{ node: Node }>(`/api/projects/${projectId}/nodes/${nodeId}`, { method: 'PATCH', body: JSON.stringify(body) }), deleteNode: (projectId: string, nodeId: string) => request(`/api/projects/${projectId}/nodes/${nodeId}`, { method: 'DELETE' }), createEdge: (projectId: string, body: object) => request<{ edge: Edge }>(`/api/projects/${projectId}/edges`, { method: 'POST', body: JSON.stringify(body) }), updateEdge: (projectId: string, edgeId: string, body: object) => request<{ edge: Edge }>(`/api/projects/${projectId}/edges/${edgeId}`, { method: 'PATCH', body: JSON.stringify(body) }), deleteEdge: (projectId: string, edgeId: string) => request(`/api/projects/${projectId}/edges/${edgeId}`, { method: 'DELETE' }), saveView: (projectId: string, body: object) => request(`/api/projects/${projectId}/view-state`, { method: 'PUT', body: JSON.stringify(body) }) };
